[build]
  base = "/backend"
  command = "npm install"   # Or your build command if needed (npm run build, etc.)
  publish = "/"             # If you are only deploying backend functions, you don't need a publish directory

[build.environment]
  PG_USER = "postgres"
  PG_HOST = "leetcodedatabase.cfxd0jlypl6m.ap-south-1.rds.amazonaws.com"
  PG_DATABASE = "leetcodedatabase"
  PG_PASSWORD = "postgres123"
  PG_PORT = "5432"
  VALIDUSER = "Admin"
  VALIDPASSWORD = "admin@123"
  
  JWT_SECRET = """
  cLY6=O9$,1h8u+}9"LO6M:lhb{WrY1`M:f~=Ho(y-$2ySb^nE1R&,yi'"~F}<>M
  """
